montes_adictos_store:
    path:     /adictos/{store}
    defaults: { _controller: MontesAdictosBundle:Store:store }

montes_adictos_store_index:
    path:     /adictos/
    defaults: { _controller: MontesAdictosBundle:Store:index }
